version: '3'

services:
  backend: 
    image: 'api-fiat'
    container_name: 'api-fiat'
    build: 
      context: .
      dockerfile: '.docker/Dockerfile'
    ports:
      - 3001:3001
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - fiat
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      fiat: 
        ipv4_address: 11.5.0.5
# # Names our volume
volumes:
  db:
    driver: local

networks:
  fiat:
    driver: bridge
    ipam:
      config:
        - subnet: 11.5.0.0/16